root = "."
tmp_dir = "tmp"

[build]
  # Lệnh build rõ ràng, dùng full path nếu cần
  cmd = "go build -o tmp/main.exe ./cmd/urlshort"
  bin = "tmp/main.exe"
  delay = 1000

  # Rất quan trọng: chỉ rõ file/extension để air nhận diện
  include_ext = ["go"]
  include_dir = ["cmd", "internal", "configs"]

  exclude_dir = ["tmp", "vendor"]

[screen]
  clear = true

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  env = [
    "UPSTASH_REDIS_URL=redis://default:ADVXA1nDcE3M2Y100jMyj0nyZ100Nl0TR1NDE0MmZmMZZ1YJcXnAAhTQ2MTU@literate-egret-54615.upstash.io:6379"
  ]